services:
  postgres:
    image: "postgres:latest"
    container_name: template-spring-boot-db
    environment:
      - "POSTGRES_DB=${DATABASE_NAME:-template_db}"
      - "POSTGRES_USER=${DATABASE_USERNAME:-postgres}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}"
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-template-network

volumes:
  postgres_data:
    driver: local

networks:
  spring-template-network:
    driver: bridge
